### ISSUE TITLE
Adding Italian option on the UI

### ISSUE THREAD

**Issue by antcalvente** [Jonur/aow-formation-share#20]
We just received the Italian translations so we are missing the option to set the application in Italian

**Comment by antcalvente** [comment]
PR with Italian translations: https://github.com/Jonur/aow-formation-share/pull/17

**Comment by Jonur** [comment]
Hi @antcalvente , fixed by this commit: f7280c014136b27cc4e5ff9f779acf3cc853cba4. Therefore, I am closing this issue. 👍🏼
