### ISSUE TITLE
[bug] sharing formation doesnt work in https://aowformationshare.jonur.io

### ISSUE THREAD

**Issue by vkarhaltsev** [Jonur/aow-formation-share#4]
when I create a formation and share it (for example: https://aowformationshare.jonur.io/?v=2&2=1DG4,9), I have a link which shows empty formation when opened in browser.

**Comment by Jonur** [comment]
Hi @vkarhaltsev , I had missed this comment for some reason. This has been fixed for a while now. I will be more active on Github now and it will be easier to communicate. Thank you for raising this regardless.
